# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MicroServiceTask.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MicroServiceTask.proto',
  package='MicroSerice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16MicroServiceTask.proto\x12\x0bMicroSerice\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\rLoginResponse\x12\x11\n\thttp_port\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\"\x08\n\x06NoType\"!\n\x10GreetingResponse\x12\r\n\x05greet\x18\x01 \x01(\t\"#\n\x0eLogoutResponse\x12\x11\n\tlogginout\x18\x01 \x01(\t\"7\n\x13\x41uthenticationToken\x12\x11\n\thttp_port\x18\x02 \x01(\x05\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x0cVerifiedUser\x12\x11\n\tverifuser\x18\x01 \x01(\t2\xd8\x01\n\nApiService\x12@\n\x05login\x12\x19.MicroSerice.LoginRequest\x1a\x1a.MicroSerice.LoginResponse\"\x00\x12=\n\x05hello\x12\x13.MicroSerice.NoType\x1a\x1d.MicroSerice.GreetingResponse\"\x00\x12I\n\x06logout\x12 .MicroSerice.AuthenticationToken\x1a\x1b.MicroSerice.LogoutResponse\"\x00\x32\xa7\x01\n\x0b\x41uthService\x12M\n\x0c\x61uthenticate\x12\x19.MicroSerice.LoginRequest\x1a .MicroSerice.AuthenticationToken\"\x00\x12I\n\x08validate\x12 .MicroSerice.AuthenticationToken\x1a\x19.MicroSerice.VerifiedUser\"\x00\x32V\n\x0cHelloService\x12\x46\n\x08SayHello\x12\x19.MicroSerice.VerifiedUser\x1a\x1d.MicroSerice.GreetingResponse\"\x00\x62\x06proto3'
)




_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='MicroSerice.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='MicroSerice.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='MicroSerice.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=89,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='MicroSerice.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='http_port', full_name='MicroSerice.LoginResponse.http_port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='MicroSerice.LoginResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=140,
)


_NOTYPE = _descriptor.Descriptor(
  name='NoType',
  full_name='MicroSerice.NoType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=150,
)


_GREETINGRESPONSE = _descriptor.Descriptor(
  name='GreetingResponse',
  full_name='MicroSerice.GreetingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greet', full_name='MicroSerice.GreetingResponse.greet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=185,
)


_LOGOUTRESPONSE = _descriptor.Descriptor(
  name='LogoutResponse',
  full_name='MicroSerice.LogoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logginout', full_name='MicroSerice.LogoutResponse.logginout', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=222,
)


_AUTHENTICATIONTOKEN = _descriptor.Descriptor(
  name='AuthenticationToken',
  full_name='MicroSerice.AuthenticationToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='http_port', full_name='MicroSerice.AuthenticationToken.http_port', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='MicroSerice.AuthenticationToken.token', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=279,
)


_VERIFIEDUSER = _descriptor.Descriptor(
  name='VerifiedUser',
  full_name='MicroSerice.VerifiedUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verifuser', full_name='MicroSerice.VerifiedUser.verifuser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=314,
)

DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['NoType'] = _NOTYPE
DESCRIPTOR.message_types_by_name['GreetingResponse'] = _GREETINGRESPONSE
DESCRIPTOR.message_types_by_name['LogoutResponse'] = _LOGOUTRESPONSE
DESCRIPTOR.message_types_by_name['AuthenticationToken'] = _AUTHENTICATIONTOKEN
DESCRIPTOR.message_types_by_name['VerifiedUser'] = _VERIFIEDUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

NoType = _reflection.GeneratedProtocolMessageType('NoType', (_message.Message,), {
  'DESCRIPTOR' : _NOTYPE,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.NoType)
  })
_sym_db.RegisterMessage(NoType)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGRESPONSE,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.GreetingResponse)
  })
_sym_db.RegisterMessage(GreetingResponse)

LogoutResponse = _reflection.GeneratedProtocolMessageType('LogoutResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTRESPONSE,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.LogoutResponse)
  })
_sym_db.RegisterMessage(LogoutResponse)

AuthenticationToken = _reflection.GeneratedProtocolMessageType('AuthenticationToken', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONTOKEN,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.AuthenticationToken)
  })
_sym_db.RegisterMessage(AuthenticationToken)

VerifiedUser = _reflection.GeneratedProtocolMessageType('VerifiedUser', (_message.Message,), {
  'DESCRIPTOR' : _VERIFIEDUSER,
  '__module__' : 'MicroServiceTask_pb2'
  # @@protoc_insertion_point(class_scope:MicroSerice.VerifiedUser)
  })
_sym_db.RegisterMessage(VerifiedUser)



_APISERVICE = _descriptor.ServiceDescriptor(
  name='ApiService',
  full_name='MicroSerice.ApiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=317,
  serialized_end=533,
  methods=[
  _descriptor.MethodDescriptor(
    name='login',
    full_name='MicroSerice.ApiService.login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='MicroSerice.ApiService.hello',
    index=1,
    containing_service=None,
    input_type=_NOTYPE,
    output_type=_GREETINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='logout',
    full_name='MicroSerice.ApiService.logout',
    index=2,
    containing_service=None,
    input_type=_AUTHENTICATIONTOKEN,
    output_type=_LOGOUTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_APISERVICE)

DESCRIPTOR.services_by_name['ApiService'] = _APISERVICE


_AUTHSERVICE = _descriptor.ServiceDescriptor(
  name='AuthService',
  full_name='MicroSerice.AuthService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=536,
  serialized_end=703,
  methods=[
  _descriptor.MethodDescriptor(
    name='authenticate',
    full_name='MicroSerice.AuthService.authenticate',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_AUTHENTICATIONTOKEN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='validate',
    full_name='MicroSerice.AuthService.validate',
    index=1,
    containing_service=None,
    input_type=_AUTHENTICATIONTOKEN,
    output_type=_VERIFIEDUSER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHSERVICE)

DESCRIPTOR.services_by_name['AuthService'] = _AUTHSERVICE


_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='MicroSerice.HelloService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=705,
  serialized_end=791,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='MicroSerice.HelloService.SayHello',
    index=0,
    containing_service=None,
    input_type=_VERIFIEDUSER,
    output_type=_GREETINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
